##### 公共 配置 #######

#内置Tomcat容器配置
server:
  port: 8092
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path:
#    context-path: /baseadmin
#基础配置
spring:
  profiles:
    active: ${BASE_ADMIN:dev} #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
  application:
    name: base-admin

  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/

  #mvc接收参数时对日期进行格式化
  #jackson对响应回去的日期参数进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    #打印SQL
    show-sql: true
    #entityMenger需要是true
    open-in-view: true

  main:
    allow-circular-references: true
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

---
##### dev 配置 #######
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/base_admin?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: yyfj8229_
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    org.springframework.data.convert.CustomConversions: ERROR

#是否需要输入验证码
captcha:
  enable: false
